title: Hippo8427의 블로그
author: Hippo8427
email: your_email@example.com
description: 자바스크립트 배우기
url: "https://hippo8427.github.io"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
collections:
  TIL:
    output: true
    permalink: /til/:name/
  WIL:
    output: true
    permalink: /wil/:name/
  WP:
    output: true
    permalink: /wp/:name/
