title: Hippo8427의 블로그
author: Hippo8427
email: your_email@example.com
description: 자바스크립트 배우기
url: "https://hippo8427.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
defaults:
  - scope:
      path: ""
    values:
      layout: default
      navigation: main







