title: Hippo8427의 블로그
author: Hippo8427
email: your_email@example.com
description: 자바스크립트 배우기
url: "https://hippo8427.github.io"
baseurl: ""
theme: minima

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: "category"

collections:
  posts:
    output: true

navigation:
  category:
    - title: "홈"
      url: /
    - title: "카테고리: 웹 개발"
      url: /categories/webdev/
    - title: "카테고리: 자바스크립트"
      url: /categories/javascript/
    - title: "카테고리: 알고리즘"
      url: /categories/algorithm/
